; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
; Community Platformio Arduino espressif32
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.04/platform-espressif32.zip
framework = arduino, espidf
monitor_speed = 115200
board_build.embed_txtfiles =
    managed_components/espressif__esp_insights/server_certs/https_server.crt
    managed_components/espressif__esp_rainmaker/server_certs/rmaker_mqtt_server.crt
    managed_components/espressif__esp_rainmaker/server_certs/rmaker_claim_service_server.crt
    managed_components/espressif__esp_rainmaker/server_certs/rmaker_ota_server.crt


[env:esp32dev]
board = esp32dev
board_build.filesystem = littlefs
board_build.partitions = partitions_custom.csv

[env:esp32-s2]
board = esp32-s2-saola-1
board_build.filesystem = littlefs
board_build.partitions = partitions_custom.csv

[env:esp32-s3]
board = esp32-s3-devkitc-1
board_build.filesystem = littlefs
board_build.partitions = partitions_custom.csv

[env:esp32-c3]
board = esp32-c3-devkitm-1
board_build.filesystem = littlefs
board_build.partitions = partitions_custom.csv

[env:esp32-c2]
board = esp32-c2-devkitm-1
board_build.filesystem = littlefs
board_build.partitions = partitions_custom.csv
 
[env:esp32-c6]
board = esp32-c6-devkitm-1
board_build.filesystem = littlefs
board_build.partitions = partitions_custom.csv
